plugins:
  - jekyll-relative-links
remote_theme: pages-themes/modernistv0.2.0
title: IPL Micro Lab
description: Bookmark this to keep an eye on my project updates!
relative_links:
  enabled: true
  collections: true
# SITE CONFIGURATION
baseurl: ""
url: "https://lciscon.github.io"
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
